FROM nginxbase:lateste
ADD nginx-proxy.conf /opt/app-root/etc/nginx.default.d/nginx-proxy.conf
ADD htpasswd /opt/app-root/etc/nginx.default.d/.htpasswd
ADD nginx.conf /etc/opt/rh/rh-nginx112/nginx/nginx.conf
